version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: navratri-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: navratri
      POSTGRES_USER: navratri
      POSTGRES_PASSWORD: navratri
    ports:
      - "5432:5432"
    volumes:
      - navratri_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: navratri-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  navratri_pg_data:
